-- Roles
CREATE TYPE public.app_role AS ENUM ('admin', 'staff', 'user');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE POLICY "users read own roles" ON public.user_roles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "admins manage roles" ON public.user_roles
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Products
CREATE TABLE public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL DEFAULT 0,
  unit text,
  is_eggless boolean NOT NULL DEFAULT false,
  is_bestseller boolean NOT NULL DEFAULT false,
  is_available boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  image_key text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.products TO anon, authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "products are public" ON public.products FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage products" ON public.products
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Orders
CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_name text NOT NULL,
  phone text NOT NULL,
  fulfilment text NOT NULL DEFAULT 'delivery',
  address text,
  landmark text,
  scheduled_date date,
  scheduled_time text,
  notes text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric(10,2) NOT NULL DEFAULT 0,
  delivery_fee numeric(10,2) NOT NULL DEFAULT 0,
  total numeric(10,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT INSERT ON public.orders TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anyone can place an order" ON public.orders FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "admins read orders" ON public.orders FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins update orders" ON public.orders FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins delete orders" ON public.orders FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Custom cake requests
CREATE TABLE public.custom_cake_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_number bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_name text NOT NULL,
  phone text NOT NULL,
  occasion text,
  flavour text,
  weight text,
  egg_preference text,
  cake_message text,
  reference_image_url text,
  fulfilment text NOT NULL DEFAULT 'pickup',
  address text,
  needed_date date,
  needed_time text,
  notes text,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT INSERT ON public.custom_cake_requests TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON public.custom_cake_requests TO authenticated;
GRANT ALL ON public.custom_cake_requests TO service_role;
ALTER TABLE public.custom_cake_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anyone can request a custom cake" ON public.custom_cake_requests FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "admins read requests" ON public.custom_cake_requests FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins update requests" ON public.custom_cake_requests FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins delete requests" ON public.custom_cake_requests FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Seed menu (indicative prices, to be replaced by the bakery)
INSERT INTO public.products (slug, name, category, description, price, unit, is_eggless, is_bestseller, sort_order, image_key) VALUES
('black-forest-cake','Black Forest Cake','Cakes','Classic chocolate sponge, cherries and fresh cream.',450,'per 500 g',false,true,1,'cake-rainbow'),
('chocolate-truffle-cake','Chocolate Truffle Cake','Cakes','Rich dark chocolate truffle, our most-ordered birthday cake.',500,'per 500 g',false,true,2,'cake-kitty'),
('pineapple-cake','Pineapple Cake','Cakes','Light pineapple sponge with fresh cream.',450,'per 500 g',false,false,3,null),
('butterscotch-cake','Butterscotch Cake','Cakes','Butterscotch cream with crunchy praline.',550,'per 500 g',false,false,4,null),
('red-velvet-cake','Red Velvet Cake','Cakes','Red velvet sponge with cream cheese frosting.',650,'per 500 g',false,true,5,'cake-anniversary'),
('vanilla-eggless-cake','Vanilla Cake (Egg-less)','Cakes','Soft egg-less vanilla sponge with fresh cream.',480,'per 500 g',true,false,6,null),
('plum-cake','Plum Cake','Cakes','Our famous seasonal plum cake, rich with dry fruit.',350,'per 500 g',false,true,7,null),
('veg-puff','Veg Puff','Puffs','Flaky puff with spiced vegetable filling.',20,'each',true,false,10,null),
('egg-puff','Egg Puff','Puffs','Boiled egg and masala in crisp puff pastry.',25,'each',false,false,11,null),
('paneer-puff','Paneer Puff','Puffs','Soft paneer masala in a buttery puff.',30,'each',true,false,12,null),
('chicken-puff','Chicken Puff','Puffs','Spiced chicken filling, baked fresh through the day.',31,'each',false,true,13,null),
('prawns-puff','Prawns Puff','Puffs','Coastal-style prawn masala puff.',40,'each',false,false,14,null),
('chocolate-pastry','Chocolate Pastry','Pastries','Chocolate sponge slice with truffle cream.',80,'each',false,true,20,null),
('pineapple-pastry','Pineapple Pastry','Pastries','Fresh cream pineapple pastry.',70,'each',false,false,21,null),
('black-forest-pastry','Black Forest Pastry','Pastries','Cherry and cream slice.',80,'each',false,false,22,null),
('cupcake','Cupcake','Pastries','Vanilla or chocolate cupcake with buttercream.',40,'each',false,false,23,null),
('milk-bread','Milk Bread','Breads','Soft daily-baked milk bread loaf.',45,'loaf',true,false,30,null),
('brown-bread','Brown Bread','Breads','Wholesome brown bread, baked fresh each morning.',55,'loaf',true,false,31,null),
('bun-pack','Buns (pack of 6)','Breads','Soft sweet buns, pack of six.',40,'pack',true,false,32,null),
('rusk','Butter Rusk','Breads','Crisp tea-time rusk.',60,'pack',true,false,33,null),
('dry-fruit-biscuits','Dry Fruit Biscuits','Desserts','Buttery biscuits loaded with dry fruit.',120,'250 g',true,false,40,null),
('chocolates-box','Assorted Chocolates','Desserts','Hand-packed chocolate box for gifting.',200,'box',true,false,41,null),
('caramel-pudding','Caramel Pudding','Desserts','Chilled caramel custard pudding.',90,'each',false,false,42,null);